export const weddingConfig = {
  names: {
    bride: "Bheatriz",
    groom: "Lucas",
    brideShort: "Bhea",
    groomShort: "Lucas",
  },
  event: {
    date: "2026-09-13T14:30:00-03:00",
    arrivalTime: "14:20",
    venueName: "Haras Pôr do Sol",
    venueAddress: "Cabedelo - PB",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Haras%20Por%20do%20Sol%20Cabedelo%20PB",
    wazeLink: "https://waze.com/ul?q=Haras%20Por%20do%20Sol%20Cabedelo%20PB&navigate=yes",
    dressCode: {
      type: "Esporte fino",
      description:
        "O casamento será à tarde, em clima de campo. Tecidos leves, tons suaves e roupas confortáveis combinam muito bem com a celebração.",
      prohibitedColors: ["Branco", "Off-white", "Pérola", "Marfim"],
    },
  },
  payment: {
    pixKey: "substitua-pela-chave-pix",
    pixHolder: "Adna Bheatriz de Oliveira Alencar",
    bank: "Banco do Brasil",
    mercadoPagoLink: "https://www.mercadopago.com.br/",
  },
  admin: {
    password: process.env.ADMIN_PASSWORD || "casamento2026",
  },
  gifts: [
    {
      id: "sofa",
      title: "Cota Sofá Confortável",
      price: 1800,
      image: "/images/gifts/sofa.png",
      category: "Sala de Estar",
      priority: 1,
    },
    {
      id: "geladeira",
      title: "Cota Geladeira Duplex",
      price: 2800,
      image: "/images/gifts/geladeira.png",
      category: "Cozinha",
      priority: 2,
    },
    {
      id: "cama",
      title: "Roupa de Cama",
      price: 300,
      image: "/images/gifts/cama.png",
      category: "Quarto",
      priority: 3,
    },
    {
      id: "microondas",
      title: "Forno Micro-ondas",
      price: 650,
      image: "/images/gifts/microondas.png",
      category: "Cozinha",
      priority: 4,
    },
    {
      id: "airfryer",
      title: "Fritadeira Elétrica Airfryer",
      price: 450,
      image: "/images/gifts/airfryer.png",
      category: "Cozinha",
      priority: 5,
    },
    {
      id: "depurador",
      title: "Depurador de Ar",
      price: 500,
      image: "/images/gifts/depurador.png",
      category: "Cozinha",
      priority: 6,
    },
    {
      id: "aspirador",
      title: "Aspirador de Pó Vertical",
      price: 300,
      image: "/images/gifts/aspirador.png",
      category: "Área de Serviço",
      priority: 7,
    },
    {
      id: "ventilador",
      title: "Ventilador de Coluna",
      price: 250,
      image: "/images/gifts/ventilador.png",
      category: "Quarto",
      priority: 8,
    },
    {
      id: "panela-eletrica",
      title: "Panela de Pressão Elétrica",
      price: 350,
      image: "/images/gifts/panela elétrica.png",
      category: "Cozinha",
      priority: 9,
    },
    {
      id: "batedeira",
      title: "Batedeira Planetária",
      price: 300,
      image: "/images/gifts/batedeira.png",
      category: "Cozinha",
      priority: 10,
    },
    {
      id: "cafeteira",
      title: "Cafeteira Elétrica",
      price: 200,
      image: "/images/gifts/cafeteira.png",
      category: "Cozinha",
      priority: 11,
    },
    {
      id: "liquidificador",
      title: "Liquidificador de Alta Potência",
      price: 220,
      image: "/images/gifts/liquidificador.png",
      category: "Cozinha",
      priority: 12,
    },
    {
      id: "cacarola-ceramica",
      title: "Caçarola de Cerâmica",
      price: 400,
      image: "/images/gifts/cacarola ceramica.png",
      category: "Cozinha",
      priority: 13,
    },
    {
      id: "ferro",
      title: "Ferro de Passar a Vapor",
      price: 150,
      image: "/images/gifts/ferro.png",
      category: "Área de Serviço",
      priority: 14,
    },
    {
      id: "travessas",
      title: "Jogo de Travessas de Vidro",
      price: 180,
      image: "/images/gifts/travessas.png",
      category: "Cozinha",
      priority: 15,
    },
    {
      id: "toalhas",
      title: "Jogo de Toalhas Macias",
      price: 160,
      image: "/images/gifts/toalhas.png",
      category: "Banheiro",
      priority: 16,
    },
    {
      id: "mixer",
      title: "Mixer Multiuso",
      price: 130,
      image: "/images/gifts/mixer.png",
      category: "Cozinha",
      priority: 17,
    },
    {
      id: "sanduicheira",
      title: "Sanduicheira e Grill",
      price: 120,
      image: "/images/gifts/sanduicheira.png",
      category: "Cozinha",
      priority: 18,
    },
    {
      id: "bule",
      title: "Bule Térmico Moderno",
      price: 90,
      image: "/images/gifts/bule.png",
      category: "Cozinha",
      priority: 19,
    },
  ],
  guests: [
    {
      id: 1,
      name: "Mariana Ferreira",
      group: "Família Ferreira",
      allowedCount: 3,
      companions: ["João Ferreira", "Ana Ferreira"],
    },
    {
      id: 2,
      name: "Carlos Almeida",
      group: "Família Almeida",
      allowedCount: 4,
      companions: ["Patrícia Almeida", "Lucas Almeida", "Clara Almeida"],
    },
    {
      id: 3,
      name: "Beatriz Lima",
      group: "Amigos da Bhea",
      allowedCount: 2,
      companions: ["Rafaela Lima"],
    },
    {
      id: 4,
      name: "Gabriel Nascimento",
      group: "Amigos do Lucas",
      allowedCount: 1,
      companions: [],
    },
    {
      id: 5,
      name: "Helena e Marcos Ribeiro",
      group: "Família Ribeiro",
      allowedCount: 2,
      companions: ["Marcos Ribeiro"],
    },
  ],
};
